"""Generate BP_config_allmarkets.yaml -- a broad "scan everything" evaluation
profile (stocks + commodities + softs + ETFs + [base forex/metals/energies/
indices/crypto]) that paper-trades a $5k / 1% account with NO challenge gating,
so it takes every qualifying signal to build a track record across all markets.

Run:  python _gen_allmarkets_config.py    (rewrites BP_config_allmarkets.yaml)
"""
import yaml

# ---- watchlist_extra (APPENDED to the base BP_config.yaml watchlist) --------
# asset_class drives COT / Valuation routing, so it must be correct.

STOCKS = [  # equities -- major liquid US large-caps across all sectors
    "AAPL","MSFT","GOOGL","GOOG","AMZN","META","NVDA","TSLA","AVGO","ORCL",
    "CRM","ADBE","AMD","INTC","CSCO","QCOM","TXN","IBM","NOW","INTU","AMAT","MU",
    "NFLX","DIS","CMCSA","VZ","TMUS","T",
    "WMT","HD","MCD","NKE","SBUX","COST","TGT","LOW","PG","KO","PEP","PM","MDLZ",
    "JPM","BAC","WFC","GS","MS","C","AXP","BLK","SCHW","V","MA",
    "UNH","JNJ","LLY","PFE","MRK","ABBV","TMO","ABT","DHR","BMY",
    "XOM","CVX","COP","SLB","OXY",
    "BA","CAT","GE","HON","UPS","RTX","LMT","DE",
    "BRK-B","BABA","PYPL","UBER","F","GM",
]

GRAINS_MEATS = ["ZC=F","ZW=F","ZS=F","ZM=F","ZL=F","ZO=F","LE=F","HE=F","GF=F"]  # commodities
SOFTS        = ["KC=F","SB=F","CC=F","CT=F","OJ=F"]                             # soft_commodities

ETF_INDEX = ["SPY","QQQ","DIA","IWM","VTI","EEM","EFA"]                 # equity_indices
ETF_SECT  = ["XLE","XLF","XLK","XLV","XLI","XLP","XLY","XLU","XLB","XLRE","XLC","SMH","SOXX"]  # equities
ETF_METAL = ["GLD","SLV"]        # precious_metals
ETF_ENERGY= ["USO","UNG"]        # energies
ETF_BONDS = ["TLT","IEF","HYG","LQD"]  # interest_rates

def entry(sym, ac, name=None):
    d = {"symbol": sym, "name": name or sym.replace("=F","").replace("-USD","USD"),
         "asset_class": ac}
    return d

wl = []
for s in STOCKS:        wl.append(entry(s, "equities"))
for s in GRAINS_MEATS:  wl.append(entry(s, "commodities"))
for s in SOFTS:         wl.append(entry(s, "soft_commodities"))
for s in ETF_INDEX:     wl.append(entry(s, "equity_indices"))
for s in ETF_SECT:      wl.append(entry(s, "equities"))
for s in ETF_METAL:     wl.append(entry(s, "precious_metals"))
for s in ETF_ENERGY:    wl.append(entry(s, "energies"))
for s in ETF_BONDS:     wl.append(entry(s, "interest_rates"))

config = {
    # Broad evaluation profile: gating OFF so it takes EVERY qualifying signal
    # across all markets and builds a track record on a $5k / 1% paper account.
    "prop_firm": {"enabled": False},
    "risk": {
        "account_balance": 5000.0,
        "risk_per_trade_pct": 1.0,
        "max_open_positions": 99999,   # take all; dedup still blocks duplicates
    },
    "active_strategy": "weekly",
    "alerts": {"min_composite_to_post": 7.0, "min_composite_to_alert": 5.5},
    "watchlist_extra": wl,
}

HEADER = (
    "# BP_config_allmarkets.yaml -- AUTO-GENERATED by _gen_allmarkets_config.py\n"
    "# Broad 'scan everything' evaluation profile (profile: allmarkets).\n"
    "# Deep-merged OVER BP_config.yaml; watchlist_extra is APPENDED to the base\n"
    "# forex/metals/energies/indices/crypto watchlist. Gating OFF, $5k / 1%,\n"
    "# take-all -- to evaluate Bernd's method across all asset classes before\n"
    f"# committing to a futures challenge. {len(wl)} extra symbols.\n\n"
)
with open("BP_config_allmarkets.yaml", "w", encoding="utf-8") as f:
    f.write(HEADER)
    yaml.safe_dump(config, f, sort_keys=False, default_flow_style=False, width=100)
print(f"Wrote BP_config_allmarkets.yaml with {len(wl)} extra symbols")
print("  stocks:", len(STOCKS), "| grains/meats:", len(GRAINS_MEATS),
      "| softs:", len(SOFTS), "| ETFs:", len(ETF_INDEX+ETF_SECT+ETF_METAL+ETF_ENERGY+ETF_BONDS))
